/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.admin;

import controller.DuyetDon;
import controller.TKDSDonDKTheoMaHP;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.FakeData;
import model.HocPhan;
import model.TTDonDangKy;
import view.dangnhap.DangNhap;

/**
 *
 * @author Le Thi Ngoc
 */
public class TKDonDKTheoHocPhan extends javax.swing.JDialog {
    private TKDSDonDKTheoMaHP model;
    private String maHP;
    private DefaultTableModel tableModel;
    /**
     * Creates new form TKDonDKTheoHocPhan
     */
    public TKDonDKTheoHocPhan(java.awt.Dialog parent, boolean modal, String maHP) {
        super(parent, modal);
        this.maHP = maHP;
        this.setTitle("Danh sách đơn đăng ký học phần " + getTenHP(this.maHP));
        initComponents();
        capNhatBang();
    }
    
    public String getTenHP(String maHP){
        String tenHP = "";
        List<HocPhan> listHP = FakeData.layHocPhan_Test();
        for(HocPhan hp : listHP)
            if(hp.getMaHP().equals(maHP))
                tenHP =  hp.getTenHP();
        return tenHP;
    }
    
    public void capNhatBang(){
        List<TTDonDangKy> dons = model.dsDonTheoMaHP(maHP);
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Mã đơn");
        tableModel.addColumn("Mã SV");
        tableModel.addColumn("Loại đơn");
        tableModel.addColumn("Số lượng SV");

        for (TTDonDangKy don : dons) {
            Object[] row = {
                    don.getMaDon(),
                    don.getMaSV(),
                    don.getLoaiDon(),
                    don.getSoLuongSV()
            };
            tableModel.addRow(row);
        }
        tbl_DonDangKy.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQuayLai = new javax.swing.JButton();
        btnDuyet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DonDangKy = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        btnDuyet.setText("Duyệt");
        btnDuyet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuyetActionPerformed(evt);
            }
        });

        tbl_DonDangKy.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        tbl_DonDangKy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã đơn", "Mã sinh viên", "Loại đơn", "Số lượng SV"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_DonDangKy);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnDuyet, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDuyet, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnDuyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuyetActionPerformed
        // TODO add your handling code here:
        DuyetDon duyet = new DuyetDon(model.dsDonTheoMaHP(maHP));
        if(DuyetDon.soLuongLopDuocMo == 0)
            JOptionPane.showMessageDialog(TKDonDKTheoHocPhan.this, "Đã duyệt! Không có lớp nào được mở do không đủ số lượng sinh viên!");
        else{
            JOptionPane.showMessageDialog(TKDonDKTheoHocPhan.this, "Đã duyệt! Có " + DuyetDon.soLuongLopDuocMo + " lớp được mở");
            DuyetDon.soLuongLopDuocMo = 0;
        }
        tableModel.setRowCount(0);
    }//GEN-LAST:event_btnDuyetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TKDonDKTheoHocPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TKDonDKTheoHocPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TKDonDKTheoHocPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TKDonDKTheoHocPhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                TKDonDKTheoHocPhan dialog = new TKDonDKTheoHocPhan(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDuyet;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_DonDangKy;
    // End of variables declaration//GEN-END:variables
}
