/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.sinhvien;

import controller.TKDSDonTheoSV;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.FakeData;
import model.TTDonDangKy;

/**
 *
 * @author Le Thi Ngoc
 */
public class DSDonDangKy extends javax.swing.JDialog {
    private TKDSDonTheoSV model;
    private String maSV = FakeData.layMaSV_Test();
    
    private static List<TTDonDangKy> donsDKTheoSV=null;
    public DSDonDangKy(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        capNhapDon();
    }
    
//    List<TTDonDangKy> donsDKTheoSV = model.dsDonTheoMaSV(maSV); 
    
    public void capNhapDon(){
        donsDKTheoSV = TKDSDonTheoSV.dsDonTheoMaSV(maSV);
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Mã đơn");
        tableModel.addColumn("Mã học phần");
        tableModel.addColumn("Tên học phần");
        tableModel.addColumn("Loại đơn");
        tableModel.addColumn("Trạng thái");
        
        for(TTDonDangKy don: donsDKTheoSV){
               Object[] row = {
                   don.getMaDon(),
                   don.getMaHP(),
                   don.getTenHP(),
                   don.getLoaiDon(),
                   don.getTrangThai()
               };
              tableModel.addRow(row);
        }
        tbl_DonDangKYSV.setModel(tableModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DonDangKYSV = new javax.swing.JTable();
        btlQuayLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl_DonDangKYSV.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        tbl_DonDangKYSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã học phần", "Tên học phần", "Loại đơn", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(tbl_DonDangKYSV);

        btlQuayLai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btlQuayLai.setText("Quay lại");
        btlQuayLai.setName("btnQuayLai"); // NOI18N
        btlQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(btlQuayLai))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btlQuayLai)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btlQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlQuayLaiActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btlQuayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSDonDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSDonDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSDonDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSDonDangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DSDonDangKy dialog = new DSDonDangKy(new javax.swing.JFrame(), true,donsDKTheoSV);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlQuayLai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_DonDangKYSV;
    // End of variables declaration//GEN-END:variables
}
